#!/usr/bin/env python3

S = input()
T = input()


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    ans = 0
    for i in range(min(len(S), len(T))):
        if S[i] != T[i]:
            ans = i + 1
            break
    else:
        if S != T:
            ans = min(len(S), len(T)) + 1

    return print(ans)


if __name__ == "__main__":
    main()
