#!/usr/bin/env python3

import itertools

N = int(input())
K = [int(x) for x in input().split()]
K = sorted(K)
ttl = sum(K)


def gt_val(r):
    res = ttl
    for arr in itertools.permutations(K, r):
        chk = max(sum(list(arr)), ttl - sum(list(arr)))
        res = min(chk, res)

    return res


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    ans = ttl
    for r in range(1, N // 2 + 1):
        ans = min(ans, gt_val(r))

    return print(ans)


if __name__ == "__main__":
    main()
