#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str

S = input()


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    if S[-3:] == "san":
        return print("Yes")
    else:
        return print("No")


if __name__ == "__main__":
    main()
